[package]
name = "tcp-struct-macros"
version = "0.3.1"
description = "Macros for tcp-struct"
license = "MIT"
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0.37"
proc-macro2 = "1.0.87"
once_cell = "1.20.2"

[lib]
proc-macro = true

[features]
async-tcp = []
